{
    'name': 'hr_hospital',
    'version': '1.1.4.0',
    'summary': 'Test cree module addon hopital',
    'description': 'Test cree modeles addon',
    'category': 'Employees',
    'author': 'Olga Holodaieva',
    'website': '',
    'license': '',
    'depends': ['base'],
    'data': ['security/ir.model.access.csv',
             'views/hr_hospital_menu.xml',
             'views/patient_view.xml',
             'views/medecin_view.xml',
             'views/personne_de_contact_view.xml',
             'views/histoir_medecin_traitant_view.xml',
             'views/diagnostic_view.xml',
             'views/patient_brefhistorique_view'],
    'demo': ['data/hr_hospital_demo.xml'],
    'installable': True,
    'application': True,
    'auto_install': True
}